'nexENCODE Studio 5.0 Alpha 1.3
'January 7th, 2012
Option Explicit On
Option Strict On
Imports System.Collections.Generic
Imports System.Text
Imports NAudio.Utils

Namespace NAudio.CoreAudioApi.Interfaces
    Enum AudioClientErrors
        NotInitialized = CInt(&H88890001UI)
        UnsupportedFormat = CInt(&H88890008UI)
        DeviceInUse = CInt(&H8889000AUI)
    End Enum

    NotInheritable Class ErrorCodes
        Private Sub New()
        End Sub

        ' AUDCLNT_ERR(n) MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, n)
        ' AUDCLNT_SUCCESS(n) MAKE_SCODE(SEVERITY_SUCCESS, FACILITY_AUDCLNT, n)
        Const SEVERITY_ERROR As Integer = 1
        Const FACILITY_AUDCLNT As Integer = &H889
        Shared ReadOnly AUDCLNT_E_NOT_INITIALIZED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H1)
        Shared ReadOnly AUDCLNT_E_ALREADY_INITIALIZED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H2)
        Shared ReadOnly AUDCLNT_E_WRONG_ENDPOINT_TYPE As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H3)
        Shared ReadOnly AUDCLNT_E_DEVICE_INVALIDATED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H4)
        Shared ReadOnly AUDCLNT_E_NOT_STOPPED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H5)
        Shared ReadOnly AUDCLNT_E_BUFFER_TOO_LARGE As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H6)
        Shared ReadOnly AUDCLNT_E_OUT_OF_ORDER As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H7)
        Shared ReadOnly AUDCLNT_E_UNSUPPORTED_FORMAT As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H8)
        Shared ReadOnly AUDCLNT_E_INVALID_SIZE As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H9)
        Shared ReadOnly AUDCLNT_E_DEVICE_IN_USE As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &HA)
        Shared ReadOnly AUDCLNT_E_BUFFER_OPERATION_PENDING As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &HB)
        Shared ReadOnly AUDCLNT_E_THREAD_NOT_REGISTERED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &HC)
        Shared ReadOnly AUDCLNT_E_EXCLUSIVE_MODE_NOT_ALLOWED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &HE)
        Shared ReadOnly AUDCLNT_E_ENDPOINT_CREATE_FAILED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &HF)
        Shared ReadOnly AUDCLNT_E_SERVICE_NOT_RUNNING As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H10)
        Shared ReadOnly AUDCLNT_E_EVENTHANDLE_NOT_EXPECTED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H11)
        Shared ReadOnly AUDCLNT_E_EXCLUSIVE_MODE_ONLY As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H12)
        Shared ReadOnly AUDCLNT_E_BUFDURATION_PERIOD_NOT_EQUAL As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H13)
        Shared ReadOnly AUDCLNT_E_EVENTHANDLE_NOT_SET As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H14)
        Shared ReadOnly AUDCLNT_E_INCORRECT_BUFFER_SIZE As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H15)
        Shared ReadOnly AUDCLNT_E_BUFFER_SIZE_ERROR As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H16)
        Shared ReadOnly AUDCLNT_E_CPUUSAGE_EXCEEDED As Integer = HResult.MAKE_HRESULT(SEVERITY_ERROR, FACILITY_AUDCLNT, &H17)
    End Class
End Namespace